### ISSUE TITLE
main.js not found

### ISSUE THREAD

**Issue by plumcube** [meshy/django-schema-graph#14]
Getting the following error out of the box.

Couldn't find main.js in the project. Is that expected?
GET http://dev.api.beeswax.com/static/schema_graph/main.js net::ERR_ABORTED 404 (Not Found)

**Comment by meshy** [comment]
@plumcube I suspect that either you haven't added the app to `INSTALLED_APPS`, or you need to run `collectstatic`.

**Comment by plumcube** [comment]
That works! Thanks so much.

**Comment by meshy** [comment]
Glad it works! Enjoy! :smiley:
