### ISSUE TITLE
[Feature Request] Toggling schema views programmatically

### ISSUE THREAD

**Issue by nileshprasad137** [meshy/django-schema-graph#30]
Hey, firstly thanks for creating this, it's awesome. This is more of a question/feature request rather than an issue.

Can we toggle schema views programmatically without removing apps from our settings file.? (Example, different url for models etc.). I am not sure if this is possible.

**Comment by meshy** [comment]
> Hey, firstly thanks for creating this, it's awesome.

Thank you! I'm really glad you're using and enjoying the project.

> Can we toggle schema views programmatically without removing apps from our settings file.? (Example, different url for models etc.). I am not sure if this is possible.

Not yet, unfortunately, but this is a feature I'd really like to introduce. I've already got a ticket for this feature (#7), so I hope you don't mind me closing this. If you have any further ideas on the subject, please post them there!
